/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Eclipse Public License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.eclipse.org/org/documents/epl-v10.php
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.eclipse.andworx.entity;

import java.io.File;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

import org.eclipse.andworx.maven.Dependency;
import org.eclipse.andworx.project.Identity;

/**
 * Project dependency attributes
 */
@Entity(name="tableDependency")
public class DependencyBean implements Dependency {
	
    /** Column name in join table for project foreign key */
	public final static String PROJECT_ID_FIELD_NAME = "project_id";

	@Column
    String groupId;
	@Column
	String artifactId;
	@Column
    String version;
	@Column
    Boolean isLibrary;
	@Column
    String path;

	/** We use this field-name so we can query for clalss fields with a certain id */
	public final static String ID_FIELD_NAME = "id";

	/** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
 	int id;

	/** This is a foreign object which just stores the id from the Project object in this table. */
    @OneToOne
    @JoinColumn(name=PROJECT_ID_FIELD_NAME, referencedColumnName="id")
	ProjectBean projectBean;

    /**
     * Construct DependencyBean object
     * @param projectBean ntity bean of Project owner
     * @param identity Repository indentity
     */
    public DependencyBean(ProjectBean projectBean, Identity identity) {
		this();
		this.projectBean = projectBean;
		this.groupId = identity.getGroupId();
		this.artifactId = identity.getArtifactId();
		this.version = identity.getVersion();
	}

	/**
	 * Mandatory for OrmLite
	 */
    DependencyBean() {
    	isLibrary = Boolean.FALSE;
    	path = "";
	}

	public void setLibrary(Boolean isLibrary) {
		this.isLibrary = isLibrary;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public String getGroupId() {
		return groupId;
	}

	public String getArtifactId() {
		return artifactId;
	}

	public String getVersion() {
		return version;
	}

	@Override
	public Identity getIdentity() {
		return new Identity(groupId, artifactId, version);
	}
	
	@Override
	public boolean isLibrary() {
		return isLibrary;
	}

	@Override
	public File getPath() {
		return new File(path);
	}
}
