/*
 * Copyright (C) 2018 The Android Open Source Project
 *
 * Licensed under the Eclipse Public License, Version 1.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.eclipse.org/org/documents/epl-v10.php
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.eclipse.andworx.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * Filter patterns to include/exclude files in source sets 
 * TODO - Implement source set filtering
 */
@Entity(name="tableFilterPattern")
public class FilterPatternBean {

	/** We use this field-name so we can query for projects with a certain id */
	public final static String ID_FIELD_NAME = "id";
    /** Column name in join table for project foreign key */
	public final static String SOURCE_SET_ID_FIELD_NAME = "source_set_id";

	/** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
 	int id;

	/** This is a foreign object which just stores the id from the SourceSet object in this table. */
    @OneToOne
    @JoinColumn(name=SOURCE_SET_ID_FIELD_NAME, referencedColumnName="id")
	SourceSetBean sourceSetBean;
    
    @Column
    String operation; // "+" for include, "-" for exclude
    @Column
    String pattern;
 
    /**
     * Construct FilterPatternBean object
     * @param sourceSetBean Bean Entity bean of source set owner
     * @param operation "+" for include, "-" for exclude
     * @param pattern Filter pattern 
     */
    public FilterPatternBean(SourceSetBean sourceSetBean, String operation, String pattern) {
    	this.sourceSetBean = sourceSetBean;
    	this.operation = operation;
    	this.pattern = pattern;
    }

	/**
	 * Mandatory for OrmLite
	 */
    FilterPatternBean() {
    }
    
	public String getOperation() {
		return operation;
	}

	public String getPattern() {
		return pattern;
	}
    
    
}
